;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="NPC.Feature.Negotiable",DevComment="")
+GameplayTagList=(Tag="NPC.Id.Bandit.ArtifactKeeper",DevComment="")
+GameplayTagList=(Tag="NPC.Id.Researcher",DevComment="")
+GameplayTagList=(Tag="NPC.Role.ArtifactOwner",DevComment="")
+GameplayTagList=(Tag="NPC.Role.QuestGiver",DevComment="")

